<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-06-23T14:49:29Z" name="Default suite" finished-at="2023-06-23T14:49:33Z" duration-ms="4144">
    <groups>
    </groups>
    <test started-at="2023-06-23T14:49:29Z" name="Default test" finished-at="2023-06-23T14:49:33Z" duration-ms="4144">
      <class name="tests.GithubFlow">
        <test-method is-config="true" signature="setUp()[pri:0, instance:tests.GithubFlow@42530531]" started-at="2023-06-23T14:49:29Z" name="setUp" finished-at="2023-06-23T14:49:32Z" duration-ms="3258" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="setObject()[pri:0, instance:tests.GithubFlow@42530531]" started-at="2023-06-23T14:49:32Z" name="setObject" finished-at="2023-06-23T14:49:32Z" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setObject -->
        <test-method signature="createRepo()[pri:0, instance:tests.GithubFlow@42530531]" started-at="2023-06-23T14:49:32Z" name="createRepo" finished-at="2023-06-23T14:49:32Z" duration-ms="10" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createRepo -->
        <test-method signature="deleteRepo()[pri:0, instance:tests.GithubFlow@42530531]" started-at="2023-06-23T14:49:32Z" name="deleteRepo" finished-at="2023-06-23T14:49:32Z" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteRepo -->
        <test-method signature="login()[pri:0, instance:tests.GithubFlow@42530531]" started-at="2023-06-23T14:49:32Z" name="login" finished-at="2023-06-23T14:49:33Z" duration-ms="645" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "java.util.Properties.getProperty(String)" because "this.prop" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "java.util.Properties.getProperty(String)" because "this.prop" is null
at tests.GithubFlow.login(GithubFlow.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="quit()[pri:0, instance:tests.GithubFlow@42530531]" started-at="2023-06-23T14:49:33Z" name="quit" finished-at="2023-06-23T14:49:33Z" duration-ms="183" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- tests.GithubFlow -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
